import type { Book } from "./types";

/** Datos de muestra (tu hoja de cálculo) para el modo demo: READHUB_DEMO=1.
 * Algunos estados/valoraciones/páginas son ilustrativos para mostrar todas las vistas. */
export const DEMO_BOOKS: Book[] = [
  {
    "id": "demo-1",
    "created_at": "2026-06-12T00:00:00Z",
    "title": "Chatter: The Voice in Our Head, Why It Matters, and How to Harness It",
    "author": "Ethan Kross",
    "cover_url": null,
    "description": null,
    "is_fiction": false,
    "genre": "Psicología & Neurociencia",
    "categories": [
      "Psicología & Neurociencia"
    ],
    "pages": 272,
    "language": null,
    "year": 2021,
    "isbn": null,
    "publisher": null,
    "status": "leido",
    "rating": 5,
    "date_started": null,
    "date_finished": "2026-05-20",
    "notes": null,
    "position": 0
  },
  {
    "id": "demo-2",
    "created_at": "2026-06-12T00:00:00Z",
    "title": "Elastic: Unlocking Your Brain's Ability to Embrace Change",
    "author": "Leonard Mlodinow",
    "cover_url": null,
    "description": null,
    "is_fiction": false,
    "genre": "Psicología & Neurociencia",
    "categories": [
      "Psicología & Neurociencia"
    ],
    "pages": 256,
    "language": null,
    "year": 2018,
    "isbn": null,
    "publisher": null,
    "status": "leyendo",
    "rating": null,
    "date_started": null,
    "date_finished": null,
    "notes": null,
    "position": 1
  },
  {
    "id": "demo-3",
    "created_at": "2026-06-12T00:00:00Z",
    "title": "The Brain That Changes Itself: Stories of Personal Triumph from the Frontiers of Neuroscience",
    "author": "Norman Doidge",
    "cover_url": null,
    "description": null,
    "is_fiction": false,
    "genre": "Psicología & Neurociencia",
    "categories": [
      "Psicología & Neurociencia"
    ],
    "pages": null,
    "language": null,
    "year": null,
    "isbn": null,
    "publisher": null,
    "status": "por_leer",
    "rating": null,
    "date_started": null,
    "date_finished": null,
    "notes": null,
    "position": 2
  },
  {
    "id": "demo-4",
    "created_at": "2026-06-12T00:00:00Z",
    "title": "Neuro Thinking: How Your Brain Decides and Learn",
    "author": "Cole Payton",
    "cover_url": null,
    "description": null,
    "is_fiction": false,
    "genre": "Psicología & Neurociencia",
    "categories": [
      "Psicología & Neurociencia"
    ],
    "pages": null,
    "language": null,
    "year": null,
    "isbn": null,
    "publisher": null,
    "status": "por_leer",
    "rating": null,
    "date_started": null,
    "date_finished": null,
    "notes": null,
    "position": 3
  },
  {
    "id": "demo-5",
    "created_at": "2026-06-12T00:00:00Z",
    "title": "The Science Behind Procrastination: How Your Brain Tricks You",
    "author": "Chloe Parkin",
    "cover_url": null,
    "description": null,
    "is_fiction": false,
    "genre": "Psicología & Neurociencia",
    "categories": [
      "Psicología & Neurociencia"
    ],
    "pages": null,
    "language": null,
    "year": null,
    "isbn": null,
    "publisher": null,
    "status": "por_leer",
    "rating": null,
    "date_started": null,
    "date_finished": null,
    "notes": null,
    "position": 4
  },
  {
    "id": "demo-6",
    "created_at": "2026-06-12T00:00:00Z",
    "title": "A Brain That Breathes: Essential Habits for an Overwhelming World",
    "author": "Jodi Wilson",
    "cover_url": null,
    "description": null,
    "is_fiction": false,
    "genre": "Psicología & Neurociencia",
    "categories": [
      "Psicología & Neurociencia"
    ],
    "pages": 208,
    "language": null,
    "year": 2018,
    "isbn": null,
    "publisher": null,
    "status": "leido",
    "rating": 4,
    "date_started": null,
    "date_finished": "2026-05-20",
    "notes": null,
    "position": 5
  },
  {
    "id": "demo-7",
    "created_at": "2026-06-12T00:00:00Z",
    "title": "El Arte de Crear Recuerdos: Cómo Hacer de tu Memoria un Aliado para Ser Más Feliz",
    "author": "Meik Wiking",
    "cover_url": null,
    "description": null,
    "is_fiction": false,
    "genre": "Desarrollo Personal & Bienestar",
    "categories": [
      "Desarrollo Personal & Bienestar"
    ],
    "pages": null,
    "language": null,
    "year": null,
    "isbn": null,
    "publisher": null,
    "status": "por_leer",
    "rating": null,
    "date_started": null,
    "date_finished": null,
    "notes": null,
    "position": 6
  },
  {
    "id": "demo-8",
    "created_at": "2026-06-12T00:00:00Z",
    "title": "El Hábito del Monje: Pequeños Pasos para Transformar tu Vida",
    "author": "Sonia Rico",
    "cover_url": null,
    "description": null,
    "is_fiction": false,
    "genre": "Desarrollo Personal & Bienestar",
    "categories": [
      "Desarrollo Personal & Bienestar"
    ],
    "pages": null,
    "language": null,
    "year": null,
    "isbn": null,
    "publisher": null,
    "status": "por_leer",
    "rating": null,
    "date_started": null,
    "date_finished": null,
    "notes": null,
    "position": 7
  },
  {
    "id": "demo-9",
    "created_at": "2026-06-12T00:00:00Z",
    "title": "Don't Believe Everything You Think: Why Your Thinking is the Beginning & End of Suffering",
    "author": "Joseph Nguyen",
    "cover_url": null,
    "description": null,
    "is_fiction": false,
    "genre": "Desarrollo Personal & Bienestar",
    "categories": [
      "Desarrollo Personal & Bienestar"
    ],
    "pages": null,
    "language": null,
    "year": null,
    "isbn": null,
    "publisher": null,
    "status": "por_leer",
    "rating": null,
    "date_started": null,
    "date_finished": null,
    "notes": null,
    "position": 8
  },
  {
    "id": "demo-10",
    "created_at": "2026-06-12T00:00:00Z",
    "title": "Mind to Matter: The Astonishing Science of How Your Thoughts Shape Your Life",
    "author": "Dawson Church",
    "cover_url": null,
    "description": null,
    "is_fiction": false,
    "genre": "Desarrollo Personal & Bienestar",
    "categories": [
      "Desarrollo Personal & Bienestar"
    ],
    "pages": null,
    "language": null,
    "year": null,
    "isbn": null,
    "publisher": null,
    "status": "por_leer",
    "rating": null,
    "date_started": null,
    "date_finished": null,
    "notes": null,
    "position": 9
  },
  {
    "id": "demo-11",
    "created_at": "2026-06-12T00:00:00Z",
    "title": "Less Mess Less Stress: Minimalist Routines to Declutter Your Life",
    "author": "Zoe McKey",
    "cover_url": null,
    "description": null,
    "is_fiction": false,
    "genre": "Desarrollo Personal & Bienestar",
    "categories": [
      "Desarrollo Personal & Bienestar"
    ],
    "pages": null,
    "language": null,
    "year": null,
    "isbn": null,
    "publisher": null,
    "status": "por_leer",
    "rating": null,
    "date_started": null,
    "date_finished": null,
    "notes": null,
    "position": 10
  },
  {
    "id": "demo-12",
    "created_at": "2026-06-12T00:00:00Z",
    "title": "A Little More Social: How Small Choices Create Unexpected Happiness, Health, and Connection",
    "author": "Nicholas Epley",
    "cover_url": null,
    "description": null,
    "is_fiction": false,
    "genre": "Desarrollo Personal & Bienestar",
    "categories": [
      "Desarrollo Personal & Bienestar"
    ],
    "pages": null,
    "language": null,
    "year": null,
    "isbn": null,
    "publisher": null,
    "status": "por_leer",
    "rating": null,
    "date_started": null,
    "date_finished": null,
    "notes": null,
    "position": 11
  },
  {
    "id": "demo-13",
    "created_at": "2026-06-12T00:00:00Z",
    "title": "Life is a Brief Opportunity for Joy",
    "author": "Will Meyerhofer",
    "cover_url": null,
    "description": null,
    "is_fiction": false,
    "genre": "Desarrollo Personal & Bienestar",
    "categories": [
      "Desarrollo Personal & Bienestar"
    ],
    "pages": null,
    "language": null,
    "year": null,
    "isbn": null,
    "publisher": null,
    "status": "por_leer",
    "rating": null,
    "date_started": null,
    "date_finished": null,
    "notes": null,
    "position": 12
  },
  {
    "id": "demo-14",
    "created_at": "2026-06-12T00:00:00Z",
    "title": "El Revolucionario Mundo de los Probióticos: Qué Son, Cómo Funcionan y para Qué Sirven",
    "author": "Dra. Olalla Otero",
    "cover_url": null,
    "description": null,
    "is_fiction": false,
    "genre": "Salud",
    "categories": [
      "Salud"
    ],
    "pages": null,
    "language": null,
    "year": null,
    "isbn": null,
    "publisher": null,
    "status": "por_leer",
    "rating": null,
    "date_started": null,
    "date_finished": null,
    "notes": null,
    "position": 13
  },
  {
    "id": "demo-15",
    "created_at": "2026-06-12T00:00:00Z",
    "title": "Do No Harm: Stories of Life, Death, and Brain Surgery",
    "author": "Henry Marsh",
    "cover_url": null,
    "description": null,
    "is_fiction": false,
    "genre": "Salud",
    "categories": [
      "Salud"
    ],
    "pages": null,
    "language": null,
    "year": null,
    "isbn": null,
    "publisher": null,
    "status": "por_leer",
    "rating": null,
    "date_started": null,
    "date_finished": null,
    "notes": null,
    "position": 14
  },
  {
    "id": "demo-16",
    "created_at": "2026-06-12T00:00:00Z",
    "title": "The Science of Meditation: How to Change Your Brain, Mind and Body",
    "author": "Daniel Goleman & Richard J. Davidson",
    "cover_url": null,
    "description": null,
    "is_fiction": false,
    "genre": "Salud",
    "categories": [
      "Salud"
    ],
    "pages": null,
    "language": null,
    "year": null,
    "isbn": null,
    "publisher": null,
    "status": "por_leer",
    "rating": null,
    "date_started": null,
    "date_finished": null,
    "notes": null,
    "position": 15
  },
  {
    "id": "demo-17",
    "created_at": "2026-06-12T00:00:00Z",
    "title": "Either/Or: A Fragment of Life",
    "author": "Søren Kierkegaard",
    "cover_url": null,
    "description": null,
    "is_fiction": false,
    "genre": "Filosofía",
    "categories": [
      "Filosofía"
    ],
    "pages": null,
    "language": null,
    "year": null,
    "isbn": null,
    "publisher": null,
    "status": "por_leer",
    "rating": null,
    "date_started": null,
    "date_finished": null,
    "notes": null,
    "position": 16
  },
  {
    "id": "demo-18",
    "created_at": "2026-06-12T00:00:00Z",
    "title": "Farmaconomía: Cómo las Grandes Farmacéuticas Contribuyen al Deterioro de la Salud Global",
    "author": "Nick Dearden",
    "cover_url": null,
    "description": null,
    "is_fiction": false,
    "genre": "Sociedad & Política",
    "categories": [
      "Sociedad & Política"
    ],
    "pages": null,
    "language": null,
    "year": null,
    "isbn": null,
    "publisher": null,
    "status": "por_leer",
    "rating": null,
    "date_started": null,
    "date_finished": null,
    "notes": null,
    "position": 17
  },
  {
    "id": "demo-19",
    "created_at": "2026-06-12T00:00:00Z",
    "title": "Sin Velo: Cómo el Privilegio de Occidente Permitió Ignorar la Represión en el Mundo Musulmán",
    "author": "Yasmine Mohammed",
    "cover_url": null,
    "description": null,
    "is_fiction": false,
    "genre": "Sociedad & Política",
    "categories": [
      "Sociedad & Política"
    ],
    "pages": 224,
    "language": null,
    "year": 2009,
    "isbn": null,
    "publisher": null,
    "status": "leido",
    "rating": 5,
    "date_started": null,
    "date_finished": "2026-05-20",
    "notes": null,
    "position": 18
  },
  {
    "id": "demo-20",
    "created_at": "2026-06-12T00:00:00Z",
    "title": "Astrophysics for People in a Hurry",
    "author": "Neil deGrasse Tyson",
    "cover_url": null,
    "description": null,
    "is_fiction": false,
    "genre": "Ciencia",
    "categories": [
      "Ciencia"
    ],
    "pages": 240,
    "language": null,
    "year": 2017,
    "isbn": null,
    "publisher": null,
    "status": "leyendo",
    "rating": null,
    "date_started": null,
    "date_finished": null,
    "notes": null,
    "position": 19
  },
  {
    "id": "demo-21",
    "created_at": "2026-06-12T00:00:00Z",
    "title": "The Meaning of It All: Thoughts of a Citizen-Scientist",
    "author": "Richard P. Feynman",
    "cover_url": null,
    "description": null,
    "is_fiction": false,
    "genre": "Ciencia",
    "categories": [
      "Ciencia"
    ],
    "pages": null,
    "language": null,
    "year": null,
    "isbn": null,
    "publisher": null,
    "status": "por_leer",
    "rating": null,
    "date_started": null,
    "date_finished": null,
    "notes": null,
    "position": 20
  },
  {
    "id": "demo-22",
    "created_at": "2026-06-12T00:00:00Z",
    "title": "A Brief History of Intelligence: Evolution, AI, and the Five Breakthroughs That Made Our Brains",
    "author": "Max Bennett",
    "cover_url": null,
    "description": null,
    "is_fiction": false,
    "genre": "Ciencia",
    "categories": [
      "Ciencia"
    ],
    "pages": null,
    "language": null,
    "year": null,
    "isbn": null,
    "publisher": null,
    "status": "por_leer",
    "rating": null,
    "date_started": null,
    "date_finished": null,
    "notes": null,
    "position": 21
  },
  {
    "id": "demo-23",
    "created_at": "2026-06-12T00:00:00Z",
    "title": "Amarse con los Ojos Abiertos: El Desarrollo Personal a Través de la Pareja",
    "author": "Jorge Bucay & Silvia Salinas",
    "cover_url": null,
    "description": null,
    "is_fiction": false,
    "genre": "Relaciones",
    "categories": [
      "Relaciones"
    ],
    "pages": null,
    "language": null,
    "year": null,
    "isbn": null,
    "publisher": null,
    "status": "por_leer",
    "rating": null,
    "date_started": null,
    "date_finished": null,
    "notes": null,
    "position": 22
  },
  {
    "id": "demo-24",
    "created_at": "2026-06-12T00:00:00Z",
    "title": "Nada se Opone a la Noche",
    "author": "Delphine de Vigan",
    "cover_url": null,
    "description": null,
    "is_fiction": true,
    "genre": "Ficción",
    "categories": [
      "Ficción"
    ],
    "pages": null,
    "language": null,
    "year": null,
    "isbn": null,
    "publisher": null,
    "status": "por_leer",
    "rating": null,
    "date_started": null,
    "date_finished": null,
    "notes": null,
    "position": 23
  },
  {
    "id": "demo-25",
    "created_at": "2026-06-12T00:00:00Z",
    "title": "The Girl in the Green Dress: A True Story of Resilience and Recovery from Trauma",
    "author": "Jeni Haynes & Dr. George Blair-West",
    "cover_url": null,
    "description": null,
    "is_fiction": true,
    "genre": "Ficción",
    "categories": [
      "Ficción"
    ],
    "pages": null,
    "language": null,
    "year": null,
    "isbn": null,
    "publisher": null,
    "status": "por_leer",
    "rating": null,
    "date_started": null,
    "date_finished": null,
    "notes": null,
    "position": 24
  },
  {
    "id": "demo-26",
    "created_at": "2026-06-12T00:00:00Z",
    "title": "How to Manifest Instantly",
    "author": "Autor por determinar",
    "cover_url": null,
    "description": null,
    "is_fiction": false,
    "genre": "Desarrollo Personal & Bienestar",
    "categories": [
      "Desarrollo Personal & Bienestar"
    ],
    "pages": null,
    "language": null,
    "year": null,
    "isbn": null,
    "publisher": null,
    "status": "por_leer",
    "rating": null,
    "date_started": null,
    "date_finished": null,
    "notes": null,
    "position": 25
  }
];
